// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/approach/mcia-strategic-framework/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approach/mcia-strategic-framework">> = Specific
  const handler = {} as typeof import("../../src/app/approach/mcia-strategic-framework/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/approach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approach">> = Specific
  const handler = {} as typeof import("../../src/app/approach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expertise/brand-traditional-marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expertise/brand-traditional-marketing">> = Specific
  const handler = {} as typeof import("../../src/app/expertise/brand-traditional-marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expertise/business-digital-transformation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expertise/business-digital-transformation">> = Specific
  const handler = {} as typeof import("../../src/app/expertise/business-digital-transformation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expertise/digital-performance-marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expertise/digital-performance-marketing">> = Specific
  const handler = {} as typeof import("../../src/app/expertise/digital-performance-marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expertise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expertise">> = Specific
  const handler = {} as typeof import("../../src/app/expertise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/digital-maturity-assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/digital-maturity-assessment">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/digital-maturity-assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/meta-ads-payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/meta-ads-payment">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/meta-ads-payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/radoss-digital/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/radoss-digital">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/radoss-digital/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/wabar-whatsapp-api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/wabar-whatsapp-api">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/wabar-whatsapp-api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work">> = Specific
  const handler = {} as typeof import("../../src/app/work/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/digital-maturity/lead/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digital-maturity/lead">> = Specific
  const handler = {} as typeof import("../../src/app/api/digital-maturity/lead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
